### ISSUE TITLE
github page fails while displaying "Installing holoviews>=1.15.1"

### ISSUE THREAD

**Issue by stepheneb** [sophiamyang/hvplot_interactive#6]
The request for this resource reported a 404 (see last mesg in console log belopw):
https://sophiamyang.github.io/hvplot_interactive/static/extensions/panel/bundled/datatabulator/tabulator-tables@5.3.2/dist/css/tabulator_simple.min.css

Copied some error listed in browser console:
```
pyparsing already loaded from default channel
pyodide.asm.js:10 packaging already loaded from default channel
pyodide.asm.js:10 bokeh already loaded from https://cdn.holoviz.org/panel/0.14.0/dist/wheels/bokeh-2.4.3-py3-none-any.whl
pyodide.asm.js:10 typing-extensions already loaded from default channel
pyodide.asm.js:10 Loading tqdm, setuptools, bleach, webencodings, six, certifi
pyodide.asm.js:10 Loaded webencodings, tqdm, certifi, setuptools, six, bleach
pyodide.asm.js:10 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 359, in run_async
    await coroutine
  File "<exec>", line 3, in <module>
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 548, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 305, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 312, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 420, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 435, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 305, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 309, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 390, in add_requirement_inner
    if self.check_version_satisfied(req):
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 336, in check_version_satisfied
    raise ValueError(
ValueError: Requested 'panel>=1.0', but panel==0.14.0 is already installed

    at new_error (pyodide.asm.js:10:218123)
    at pyodide.asm.wasm:0xdef7c
    at pyodide.asm.wasm:0xe37ae
    at method_call_trampoline (pyodide.asm.js:10:218037)
    at pyodide.asm.wasm:0x126317
    at pyodide.asm.wasm:0x1f6f2e
    at pyodide.asm.wasm:0x161a32
    at pyodide.asm.wasm:0x126827
    at pyodide.asm.wasm:0x126921
    at pyodide.asm.wasm:0x1269c4
    at pyodide.asm.wasm:0x1e0697
    at pyodide.asm.wasm:0x1da6a5
    at pyodide.asm.wasm:0x126a07
    at pyodide.asm.wasm:0x1e248c
    at pyodide.asm.wasm:0x1e00d9
    at pyodide.asm.wasm:0x1da6a5
    at pyodide.asm.wasm:0x126a07
    at pyodide.asm.wasm:0xe347a
    at Module.callPyObjectKwargs (pyodide.asm.js:10:119064)
    at Module.callPyObject (pyodide.asm.js:10:119442)
    at wrapper (pyodide.asm.js:10:183746)
tabulator_simple.min.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
```

**Comment by stepheneb** [comment]
screenshot
![image](https://github.com/sophiamyang/hvplot_interactive/assets/7188/3dd356fc-595d-4a28-9bb0-1b6c56148cb4)
